### ISSUE TITLE
Dynamic model view_sql definitions fail to generate when primary_key_name is blank, after master association key change

### ISSUE THREAD

**Issue by philayres** [consected/restructure#1467]
## Problem

Creating a dynamic model backed by `_configurations.view_sql` fails to generate its implementation class:

```
Failure creating dynamic model definition. #<NoMethodError: undefined method 'to_sym' for nil>
app/models/dynamic_model.rb:275:in 'DynamicModel::TestBlankPkView.master_primary_key_name'
app/models/concerns/user_handler.rb:101:in 'UserHandler::ClassMethods#assoc_rules'
app/models/concerns/user_handler.rb:44:in 'block in <module:UserHandler>'
app/models/dynamic_model.rb:312:in 'DynamicModel#generate_model'
```

The definition is saved but its implementation class is never generated, so the model is unusable until the definition is saved again once the view exists.

## Root cause

This is a regression of #1304, introduced by the crosswalk association work in #1399 (commit `254f89305`).

#1399 correctly changed `Master.has_many ..., primary_key:` and `UserHandler#assoc_rules`'s `belongs_to :master, primary_key:` to use the new `DynamicModel#master_primary_key_name` instead of `primary_key_name`, so that the masters-side join column is no longer conflated with the dynamic model's own record key. That was one of its acceptance criteria:

> The masters-side join column is configurable independently of the dynamic model's own primary key, or is derived from the foreign key name, so that `primary_key_name` no longer has to serve both purposes.

But the new method only *partly* separated the two. Its fallback branch still returned the dynamic model's own key:

```ruby
def master_primary_key_name
  if foreign_key_name.present? && Master.crosswalk_attr?(foreign_key_name)
    foreign_key_name
  else
    primary_key_name   # <- the dynamic table's own key, not a masters column
  end
end
```

Two consequences:

1. **The #1304 crash returns.** `DynamicModel#set_keys_from_columns` is a `before_create` that bails out when the table or view does not exist yet. A `view_sql` definition has no view at creation time (the migration that creates it runs afterwards), so `primary_key_name` stays blank. The generated class then calls `definition.master_primary_key_name.to_sym` with no blank guard — unlike its sibling `primary_key_name`, which #1304 had already guarded — and raises. If a blank string is stored rather than nil, it instead yields the empty `:""` symbol and produces `PG::SyntaxError: zero-length delimited identifier` when `master` is loaded, exactly as originally reported in #1304.

2. **A non-`id` primary key names a masters column that does not exist.** For any definition whose *Primary key name* is not `id` (a view or table with its own key column) and whose *Foreign key name* is `master_id`, the association is built as `primary_key: <that column>` against the masters table, which has no such column.

## Expected behaviour

`master_primary_key_name` names the column **on the masters table** that `foreign_key_name` values are matched against, for a direct master association:

| Configuration | Expected |
| --- | --- |
| *Foreign key name* blank (standalone) | no master association at all |
| *Foreign key name* `master_id` | `masters.id`, regardless of the dynamic table's own primary key |
| *Foreign key name* a crosswalk column (`msid`, `pro_id`, `pro_info_id`, `contact_id`) | the same-named column on masters |
| `_configurations.foreign_key_through_external_id` set | not applicable — the join is made on the external identifier's own ID column, through its own associations |

## Documentation

`docs/admin_reference/general/scoping.md` also contradicts itself following #1399. The "external ID column" section still states:

> Setting *Foreign key name* to a column other than `master_id` **without** also setting `foreign_key_through_external_id` is not supported.

That predates #1399, which made masters crosswalk columns a supported direct foreign key — as the very next section of the same page now describes.

## Acceptance criteria

- A `view_sql` dynamic model with a blank *Primary key name* generates its implementation class without raising, and its `master` association loads.
- A definition whose *Primary key name* is not `id` still joins to `masters.id` when its *Foreign key name* is `master_id`.
- Crosswalk and `foreign_key_through_external_id` definitions are unaffected.
- The three association helpers are commented so the masters-side versus own-table distinction is not lost again.
- `scoping.md` no longer contradicts itself about which foreign keys are supported.

Regression of #1304. Introduced by #1399.
